name: Run CI Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - 'main'
jobs:
  run-copywrite:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-copywrite@v1.1.3
      - name: verify copyright
        run: |
          copywrite --config .github/workflows/scripts/copywrite.hcl \
            headers --spdx "BSD-3-Clause" --plan
  run-lint:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1
          skip-cache: true
          args: --config .github/workflows/scripts/golangci.yaml
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: '**/go.sum'
      - name: Run Go Vet
        run: |
          go vet ./...
      - name: Run Go Fmt
        run: |
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "Please run gofmt on these files ..."
            echo "$files"
            exit 1
          fi
      - name: Run Go Test
        run: |
          go test -race -v ./...
